# Site
repository: maxvandermeij/github.io
# favicon: images/favicon.ico

# Personal info
name: Max van der Meij 
title: DevOps Engineer
email: max.van.der.meij@devoteam.com
website: vexit.nl

# Social links
#twitter_username: 
github_username:  maxvandermeij
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: 
linkedin_username: maxvandermeij
# pinterest_username: jekyll
#youtube_username: 
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 I am a technology generalist with the ability to understand and effectively use new technology quickly. My work-time hobby is designing and creating practical solutions for IT development and operations. While doing so, I enjoy questioning the current way of doing things and automating tasks as much as possible. In addition, sharing knowledge and in turn learning from others is part of my way of work. 

  I am most skilled in: <mark>Containerisation</mark> and <mark>Orchestration</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in development and operations engineering some of my other interests and hobbies are:
   - Bouldering 
   - Gardening
   - Cooking
   - Board-gaming

# Footer
footer_show_references: false 

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
